# Generated by Django 4.0.1 on 2024-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events_attending', to='api.Attendee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='roomids',
            field=models.ManyToManyField(blank=True, related_name='events_roomid', to='api.RoomId'),
        ),
        migrations.AlterField(
            model_name='event',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='events_scheduled', to='api.Schedule'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events_speaking', to='api.Speaker'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='events_sponsor', to='api.Sponsor'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_groups', related_query_name='customuser_group', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions', related_query_name='customuser_permission', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
